### ISSUE TITLE
Additional fields are no exclude fields

### ISSUE THREAD

**Issue by kkugelmann** [jpmschuler/TYPO3-powermail-limits#1]
Hey there,

first of all thanks for this extension.

We'll give it a try but found out, that the additional fields in powermails form model are no exclude fields an cannot be added/removed with be user permissions.

Is this due to a certain reason or did you just not need it until now?

If there is no reason not to have them configured as exclude fields, could you change them to exclude fields / merge such an MR?

cheers

Korbinian

**Comment by jpmschuler** [comment]
Oh indeed, a leftover for easier debugging, v0.1.7 has exclude set to true.

Please report back if the extension works in the wild as you expect so that I can mark it as a v1.0.0 - our own project has ~4 weeks left for the full test with editors.

**Comment by jpmschuler** [comment]
https://packagist.org/packages/jpmschuler/powermail-limits#v0.1.7

**Comment by kkugelmann** [comment]
Oh wow, thank you very much for the fast response :)

I will let you know if everything is fine :)
