### ISSUE TITLE
TYPO3 12

### ISSUE THREAD

**Issue by jacques2017** [jpmschuler/TYPO3-powermail-limits#3]
Hi,
is it planned to make this extension compatible to TYPO3 12 and Powermail 11

**Comment by jpmschuler** [comment]
Sure thing, although I currently have no system at hand for thorough tests, so my pessimistic schedule would be Feb/March.

However concrete bug reports or a full blown PR are welcome of course

**Comment by jpmschuler** [comment]
v2.0.1 was released with #4 
(beware TER lists v2.0.0 as 11LTS-compatible, that is not true; the last version with 11LTS-compatibility is v1.0.4)
